@server=http://localhost:4004


### Documents
# @name Documents_GET
GET {{server}}/odata/v4/document-intelligence/Documents



### Documents
# @name Documents_POST
POST {{server}}/odata/v4/document-intelligence/Documents
Content-Type: application/json

{
  "ID": "1110916c-2ba7-4130-8a42-179dc506a84f",
  "rawText": "rawText-1110916",
  "fileName": "fileName-1110916",
  "uploadedBy": "uploadedBy-1110916",
  "uploadedAt": "2011-02-13T00:00:00.000Z",
  "status": "Failed",
  "invoice": [
    {
      "ID": "22283493-ba88-4f5e-89cd-20e3cc95f71a",
      "document": {
        "ID": "1110916c-2ba7-4130-8a42-179dc506a84f"
      },
      "invoiceNumber": "invoiceNumber-22283493",
      "vendorName": "vendorName-22283493",
      "invoiceDate": "2019-05-07",
      "totalAmount": 8816761819425.94,
      "currency": "493",
      "confidence": 3.674,
      "lineItems": [
        {
          "ID": "91924bd7-2223-41a9-9d76-97a1d9e1cbe3",
          "description": "description-91924",
          "quantity": 9282265.508,
          "unitPrice": 7812350317407.25,
          "lineTotal": 9661338905244.89
        },
        {
          "ID": "91925220-15b7-41de-88e7-a96254fa49fe",
          "description": "description-91925",
          "quantity": 762120.23,
          "unitPrice": 2006536341816.25,
          "lineTotal": 4890785600964.88
        }
      ],
      "createdAt": "2021-01-30T00:00:00.000Z",
      "createdBy": "createdBy.d9m1x@example.com",
      "modifiedAt": "2008-02-28T00:00:00.000Z",
      "modifiedBy": "modifiedBy.d9m1x@example.org"
    }
  ],
  "createdAt": "2023-10-12T00:00:00.000Z",
  "createdBy": "createdBy.nt6s@example.com",
  "modifiedAt": "2020-02-29T00:00:00.000Z",
  "modifiedBy": "modifiedBy.nt6s@example.com"
}


### Documents
# @name Documents_PATCH
PATCH {{server}}/odata/v4/document-intelligence/Documents/f67f8294-3705-4d06-9700-e23122dfc13f
Content-Type: application/json

{
  "invoice_ID":"0ac86c69-bcfe-4b00-986b-e5dde703b129"
}


### Documents
# @name Documents_DELETE
DELETE {{server}}/odata/v4/document-intelligence/Documents/1110916c-2ba7-4130-8a42-179dc506a84f
Content-Type: application/json


### ExtractedInvoices
# @name ExtractedInvoices_GET
GET {{server}}/odata/v4/document-intelligence/ExtractedInvoices



### ExtractedInvoices
# @name ExtractedInvoices_POST
POST {{server}}/odata/v4/document-intelligence/ExtractedInvoices
Content-Type: application/json

{
  "ID": "22283493-ba88-4f5e-89cd-20e3cc95f71a",
  "document": {
    "ID": "1110916c-2ba7-4130-8a42-179dc506a84f"
  },
  "invoiceNumber": "invoiceNumber-22283493",
  "vendorName": "vendorName-22283493",
  "invoiceDate": "2019-05-07",
  "totalAmount": 8816761819425.94,
  "currency": "493",
  "confidence": 3.674,
  "lineItems": [
    {
      "ID": "91924bd7-2223-41a9-9d76-97a1d9e1cbe3",
      "description": "description-91924",
      "quantity": 9282265.508,
      "unitPrice": 7812350317407.25,
      "lineTotal": 9661338905244.89
    },
    {
      "ID": "91925220-15b7-41de-88e7-a96254fa49fe",
      "description": "description-91925",
      "quantity": 762120.23,
      "unitPrice": 2006536341816.25,
      "lineTotal": 4890785600964.88
    }
  ],
  "createdAt": "2021-01-30T00:00:00.000Z",
  "createdBy": "createdBy.d9m1x@example.com",
  "modifiedAt": "2008-02-28T00:00:00.000Z",
  "modifiedBy": "modifiedBy.d9m1x@example.org"
}


### ExtractedInvoices
# @name ExtractedInvoices_PATCH
PATCH {{server}}/odata/v4/document-intelligence/ExtractedInvoices/22283493-ba88-4f5e-89cd-20e3cc95f71a
Content-Type: application/json

{
  "ID": "22283493-ba88-4f5e-89cd-20e3cc95f71a",
  "document": {
    "ID": "1110916c-2ba7-4130-8a42-179dc506a84f"
  },
  "invoiceNumber": "invoiceNumber-22283493",
  "vendorName": "vendorName-22283493",
  "invoiceDate": "2019-05-07",
  "totalAmount": 8816761819425.94,
  "currency": "493",
  "confidence": 3.674,
  "lineItems": [
    {
      "ID": "91924bd7-2223-41a9-9d76-97a1d9e1cbe3",
      "description": "description-91924",
      "quantity": 9282265.508,
      "unitPrice": 7812350317407.25,
      "lineTotal": 9661338905244.89
    },
    {
      "ID": "91925220-15b7-41de-88e7-a96254fa49fe",
      "description": "description-91925",
      "quantity": 762120.23,
      "unitPrice": 2006536341816.25,
      "lineTotal": 4890785600964.88
    }
  ],
  "createdAt": "2021-01-30T00:00:00.000Z",
  "createdBy": "createdBy.d9m1x@example.com",
  "modifiedAt": "2008-02-28T00:00:00.000Z",
  "modifiedBy": "modifiedBy.d9m1x@example.org"
}


### ExtractedInvoices
# @name ExtractedInvoices_DELETE
DELETE {{server}}/odata/v4/document-intelligence/ExtractedInvoices/22283493-ba88-4f5e-89cd-20e3cc95f71a
Content-Type: application/json


### LineItems
# @name LineItems_GET
GET {{server}}/odata/v4/document-intelligence/LineItems



### LineItems
# @name LineItems_POST
POST {{server}}/odata/v4/document-intelligence/LineItems
Content-Type: application/json

{
  "ID": "91924bd7-2223-41a9-9d76-97a1d9e1cbe3",
  "description": "description-91924",
  "quantity": 9282265.508,
  "unitPrice": 7812350317407.25,
  "lineTotal": 9661338905244.89
}


### LineItems
# @name LineItems_PATCH
PATCH {{server}}/odata/v4/document-intelligence/LineItems/91924bd7-2223-41a9-9d76-97a1d9e1cbe3
Content-Type: application/json

{
  "ID": "91924bd7-2223-41a9-9d76-97a1d9e1cbe3",
  "description": "description-91924",
  "quantity": 9282265.508,
  "unitPrice": 7812350317407.25,
  "lineTotal": 9661338905244.89
}


### LineItems
# @name LineItems_DELETE
DELETE {{server}}/odata/v4/document-intelligence/LineItems/91924bd7-2223-41a9-9d76-97a1d9e1cbe3
Content-Type: application/json


### AuditLogs
# @name AuditLogs_GET
GET {{server}}/odata/v4/document-intelligence/AuditLogs



### processDocument
# @name processDocument_POST
POST {{server}}/odata/v4/document-intelligence/processDocument
Content-Type: application/json

{
  "documentId": "2a7405d4-1dc9-4a2e-ad67-ed4b374d90d9"
}


### uploadDocument
# @name uploadDocument_POST
POST {{server}}/odata/v4/document-intelligence/uploadDocument
Content-Type: application/json

{
  "rawText": "rawText-23287900",
  "fileName": "fileName-23287900"
}
